[package]
name = "platform-layershell"
version = "0.1.0"
edition = "2024"

[dependencies]
telar = { workspace = true }
smithay-client-toolkit = { workspace = true }
wayland-client = { workspace = true, features = ["log"] }
raw-window-handle = { workspace = true }
tracing = "0.1"
wayland-protocols = { version = "0.32.13", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
