//! Lifts the doc comments off `src/core/config.rs` so `hyprshell config schema` can annotate the defaults it
//! prints.
//!
//! Generated rather than hand-maintained because a hand-written reference is a second copy of the truth, and the
//! copy is always the one that goes stale — the roadmap's whole reason for L9. A scanner rather than a parser:
//! the file is one crate's own source in a known shape (a `///` run, then `pub struct X {` or ` pub field:`), so
//! matching that shape costs a few dozen lines instead of a syn dependency.
//!
//! Anything it fails to recognise is simply not annotated. A missed comment costs a bare key in the printed schema;
//! it can never fail the build, which is the right trade for documentation.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let source = Path::new("src/core/config.rs");
    println!("cargo:rerun-if-changed={}", source.display());
    let text = std::fs::read_to_string(source).unwrap_or_default();

    let mut entries = String::new();
    let mut types = String::new();
    let mut pending: Vec<String> = Vec::new();
    let mut current_struct = String::new();

    for line in text.lines() {
        let trimmed = line.trim();
        if let Some(doc) = trimmed
            .strip_prefix("/// ")
            .or_else(|| (trimmed == "///").then_some(""))
        {
            pending.push(doc.to_string());
            continue;
        }
        // An attribute sits between the doc comment and the item it documents, so it must not clear the run.
        if trimmed.starts_with("#[") {
            continue;
        }
        if let Some(name) = struct_name(trimmed) {
            current_struct = name;
            push(&mut entries, &current_struct, "", &pending);
        } else if let Some(field) = field_name(trimmed)
            && !current_struct.is_empty()
        {
            push(&mut entries, &current_struct, &field, &pending);
            if let Some(kind) = field_type(trimmed) {
                let _ = writeln!(types, "    ({current_struct:?}, {field:?}, {kind:?}),");
            }
        }
        pending.clear();
    }

    let out = std::path::PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    let generated = format!(
        "/// `(struct, field, doc)`; an empty field is the struct's own comment. Generated by `build.rs`.\n\
         pub static CONFIG_DOCS: &[(&str, &str, &str)] = &[\n{entries}];\n\n\
         /// `(struct, field, type)` for every `pub` field, documented or not. What lets the schema annotate a\n\
         /// nested table (`[theme.scale]`) from the struct that actually backs it.\n\
         pub static CONFIG_FIELD_TYPES: &[(&str, &str, &str)] = &[\n{types}];\n"
    );
    std::fs::write(out.join("config_docs.rs"), generated).expect("write config_docs.rs");
}

/// `    pub scale: ScaleConfig,` → `ScaleConfig`. Only the bare name is wanted, so a wrapped type
/// (`Option<FontSpec>`, `HashMap<String, PathBuf>`) yields nothing rather than a guess about which parameter
/// matters — a nested table is only ever a plain struct here.
fn field_type(line: &str) -> Option<String> {
    let (_, rest) = line.split_once(':')?;
    let kind = rest.trim().trim_end_matches(',').trim();
    let plain = !kind.is_empty()
        && kind.chars().all(|c| c.is_ascii_alphanumeric())
        && kind.starts_with(|c: char| c.is_ascii_uppercase());
    plain.then(|| kind.to_string())
}

/// `pub struct Name {` → `Name`. Tuple and unit structs carry no fields worth documenting, so they are skipped.
fn struct_name(line: &str) -> Option<String> {
    let rest = line.strip_prefix("pub struct ")?;
    let name = rest.split([' ', '{', '<', '(']).next()?.trim();
    line.ends_with('{').then(|| name.to_string())
}

/// `    pub field: Type,` → `field`. Only `pub` fields, since a private one is not config.
fn field_name(line: &str) -> Option<String> {
    let rest = line.strip_prefix("pub ")?;
    let name = rest.split(':').next()?.trim();
    let named = !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    (named && rest.contains(':')).then(|| name.to_string())
}

fn push(entries: &mut String, structure: &str, field: &str, docs: &[String]) {
    if docs.is_empty() {
        return;
    }
    let doc = docs.join("\n");
    let _ = writeln!(entries, "    ({:?}, {:?}, {:?}),", structure, field, doc);
}
