//! The prose documentation under `docs/`, and the three pages of it that are generated.
//!
//! Same argument as [`super::man`], applied to the other audience. The manual is what a distribution installs;
//! `docs/` is what someone reads on the web before installing anything, and a reference typed out there is a
//! third copy of the command table and the config schema — two of which would be wrong by the next release.
//! So `docs/reference/` is walked out of the same two tables the manual is, and only the *prose* pages are
//! written by hand.
//!
//! The other half is what keeps the hand-written pages honest. Every feature page carries front matter naming
//! the dependencies, config sections and IPC targets it describes, **by id**, and the checks below fail if a
//! page names one that does not exist — or if a module exists that no page describes. A page that drifts from
//! the build is a test failure rather than something a reader discovers.
//!
//! Test-only on purpose: nothing here is reachable from the running shell. Exposing it as a command would put
//! a documentation generator in the IPC table, which is a surface users would have to be told to ignore.
#![cfg(test)]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use std::path::{Path, PathBuf};

use config::schema::{Entry, Table};
use util::deps::{self, Kind, Need};

use super::commands::TARGETS;

const GENERATED: &str = "<!-- Generated by `UPDATE_DOCS=1 cargo test -p hyprshell --lib docs`. Do not edit by hand. -->";

/// The repository's `docs/` directory.
fn docs_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../docs")
}

/// Text safe inside a markdown table cell: a pipe would end the column and a newline the row.
fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

/// A doc comment as markdown, indented to sit under a list item.
fn indented(doc: &str) -> String {
    doc.lines()
        .map(|line| {
            if line.trim().is_empty() {
                String::new()
            } else {
                format!("  {line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// `docs/reference/commands.md`: every target and command, walked out of [`TARGETS`].
fn commands_page() -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{GENERATED}\n\n\
         # Commands\n\n\
         Every action the shell has, as of this build. `hyprshell --list` prints the same table from the\n\
         binary you are running, and `man ./man/hyprshell.1` is the manual form.\n\n\
         A request is a target, a command and its arguments. Replies begin with `ok` or `err`, and the exit\n\
         status mirrors that — see [Scripting](../guides/scripting.md).\n"
    );
    for target in TARGETS {
        let _ = writeln!(out, "## `{}`\n", target.name);
        let _ = writeln!(out, "| Command | Arguments | What it does |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for command in target.commands {
            let args = if command.args.is_empty() {
                String::new()
            } else {
                format!("`{}`", cell(command.args))
            };
            let _ = writeln!(
                out,
                "| `{}` | {args} | {} |",
                cell(command.name),
                cell(command.help)
            );
        }
        out.push('\n');
    }
    out
}

/// `docs/reference/config.md`: every section and key, walked out of the same outline `config schema` prints.
fn config_page() -> Result<String, String> {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{GENERATED}\n\n\
         # Configuration reference\n\n\
         Every key of `~/.config/hyprshell/config.toml`, as of this build. Each is optional: the default shown\n\
         is what the shell uses when the key is absent, so a working config is any subset of this page.\n\n\
         `hyprshell config schema` prints the same tree as a complete, valid config file, and\n\
         `hyprshell config schema <section>` prints one section. Both come from the running build.\n\n\
         A file under `~/.config/hyprshell/monitors/<output>/` has the same shape and overrides the global one\n\
         for that monitor — see [Per-monitor setup](../guides/per-monitor.md).\n"
    );
    for table in &config::schema::outline(None)? {
        render_table(table, 2, &mut out);
    }
    // A key whose prose already ended a paragraph, followed by the separator every section ends with, leaves a double blank line. Collapsing here beats threading "did the last entry write prose" through the walk.
    while out.contains("\n\n\n") {
        out = out.replace("\n\n\n", "\n\n");
    }
    Ok(out)
}

/// One table and everything under it. A sub-table becomes a heading of its own rather than an indent, which is
/// what the file itself does: `[theme.scale]` is a header a reader types.
fn render_table(table: &Table, depth: usize, out: &mut String) {
    let _ = writeln!(out, "{} `[{}]`\n", "#".repeat(depth), table.path);
    if let Some(doc) = table.doc {
        let _ = writeln!(out, "{doc}\n");
    }
    // The outline orders a table's own keys before its sub-tables and lists, so one pass emits each heading after the keys that belong to it rather than before them.
    let mut wrote_key = false;
    for entry in &table.entries {
        match entry {
            Entry::Key { name, default, doc } => {
                let default = match default {
                    Some(value) => format!("default `{}`", value),
                    None => "unset by default".to_string(),
                };
                let _ = writeln!(out, "- **`{name}`** · {default}");
                if let Some(doc) = doc {
                    let _ = writeln!(out, "\n{}\n", indented(doc));
                }
                wrote_key = true;
            }
            Entry::Table(nested) => {
                if wrote_key {
                    out.push('\n');
                    wrote_key = false;
                }
                render_table(nested, depth + 1, out);
            }
            Entry::List {
                path,
                doc,
                elements,
            } => {
                if wrote_key {
                    out.push('\n');
                    wrote_key = false;
                }
                let _ = writeln!(out, "{} `[[{path}]]`\n", "#".repeat(depth + 1));
                if let Some(doc) = doc {
                    let _ = writeln!(out, "{doc}\n");
                }
                out.push_str("The entries a fresh install starts with:\n\n```toml\n");
                for (index, element) in elements.iter().enumerate() {
                    if index > 0 {
                        out.push('\n');
                    }
                    let _ = writeln!(out, "[[{path}]]");
                    out.push_str(&toml::to_string(element).unwrap_or_default());
                }
                out.push_str("```\n\n");
            }
        }
    }
    if wrote_key {
        out.push('\n');
    }
}

/// `docs/reference/dependencies.md`: every external thing the shell can reach for, out of [`deps::ALL`].
fn dependencies_page() -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{GENERATED}\n\n\
         # Dependencies\n\n\
         Every external thing hyprshell can reach for, as of this build. `hyprshell deps list` answers the same\n\
         table *for this machine*, and `hyprshell deps missing` narrows it to what is absent.\n\n\
         **Required** means the process does not start without it. Everything else degrades: see\n\
         [Dependencies](../getting-started/dependencies.md) for what that guarantees.\n"
    );
    for need in [Need::Required, Need::Optional] {
        let _ = writeln!(
            out,
            "## {}\n",
            match need {
                Need::Required => "Required",
                Need::Optional => "Optional",
            }
        );
        let _ = writeln!(out, "| Id | Found as | What it is for | Without it |");
        let _ = writeln!(out, "| --- | --- | --- | --- |");
        for entry in deps::ALL.iter().filter(|entry| entry.need == need) {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | {} |",
                cell(entry.id),
                cell(&describe_kind(&entry.kind)),
                cell(entry.what),
                cell(entry.without)
            );
        }
        out.push('\n');
    }
    out.push_str(
        "## How each is probed\n\n\
         | Found as | Probed by |\n\
         | --- | --- |\n\
         | program | running it — being installed and running here are different questions |\n\
         | D-Bus name | asking the broker who owns it, *and* whether it is activatable |\n\
         | kernel interface | whether the directory exists and has anything in it |\n\
         | library | opening it, in the same order the loader uses |\n\
         | Wayland protocol | asking the compositor's registry for every interface by name |\n\n\
         A Wayland protocol can only be asked of a compositor, so from a process with no session the answer is\n\
         *unknown* rather than absent — which is not the same claim.\n",
    );
    out
}

fn describe_kind(kind: &Kind) -> String {
    match kind {
        Kind::Program { name, .. } => format!("program `{name}`"),
        Kind::Bus { name, system } => format!(
            "{} bus name `{name}`",
            if *system { "system" } else { "session" }
        ),
        Kind::Kernel { path } => format!("kernel interface `{path}`"),
        Kind::Library { sonames } => format!(
            "library `{}`, loaded at runtime",
            sonames.first().copied().unwrap_or_default()
        ),
        Kind::Protocol { interfaces } => format!(
            "Wayland protocol — {}",
            interfaces
                .iter()
                .map(|name| format!("`{name}`"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// `docs/features/README.md`: the index, walked out of every feature page's own front matter.
fn feature_index(pages: &[Page]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "{GENERATED}\n\n\
         # Features\n\n\
         One page per feature. Each says what it is for, what it needs, and how it behaves without that —\n\
         never what a key defaults to, which is [`hyprshell config schema`](../reference/config.md)'s job.\n\n\
         **Needs** names dependency ids from [`hyprshell deps list`](../reference/dependencies.md). Whether an\n\
         id is a Wayland protocol, a D-Bus peer, a kernel interface, a program or a library is declared there,\n\
         not repeated here.\n"
    );
    for (kind, heading) in [
        ("module", "Modules — what goes on a bar"),
        ("surface", "Surfaces — where the shell draws"),
        ("system", "System — what it does with no chip involved"),
        ("theming", "Theming"),
    ] {
        let _ = writeln!(out, "## {heading}\n");
        let _ = writeln!(out, "| Page | What it is | Needs |");
        let _ = writeln!(out, "| --- | --- | --- |");
        for page in pages.iter().filter(|page| page.kind() == kind) {
            let needs = if page.list("deps").is_empty() {
                "—".to_string()
            } else {
                page.list("deps")
                    .iter()
                    .map(|id| format!("`{id}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let hyprland = if page.scalar("compositor") == Some("hyprland") {
                " **(Hyprland only)**"
            } else {
                ""
            };
            let _ = writeln!(
                out,
                "| [{}]({}) | {}{hyprland} | {needs} |",
                cell(page.scalar("title").unwrap_or(&page.id)),
                page.relative,
                cell(page.scalar("summary").unwrap_or_default())
            );
        }
        out.push('\n');
    }
    out
}

/// One documentation page's front matter, plus where it lives.
struct Page {
    id: String,
    /// Path relative to `docs/features/`, for the index's links.
    relative: String,
    /// Path relative to `docs/`, for an assertion that names the file.
    label: String,
    fields: BTreeMap<String, Field>,
}

enum Field {
    Scalar(String),
    List(Vec<String>),
}

impl Page {
    fn kind(&self) -> &str {
        self.scalar("kind").unwrap_or_default()
    }

    fn scalar(&self, key: &str) -> Option<&str> {
        match self.fields.get(key) {
            Some(Field::Scalar(value)) => Some(value),
            _ => None,
        }
    }

    fn list(&self, key: &str) -> Vec<String> {
        match self.fields.get(key) {
            Some(Field::List(values)) => values.clone(),
            Some(Field::Scalar(value)) => vec![value.clone()],
            None => Vec::new(),
        }
    }

    /// Every module id this page describes — `ids` where a page covers several, else its own.
    fn module_ids(&self) -> Vec<String> {
        let ids = self.list("ids");
        if ids.is_empty() {
            vec![self.id.clone()]
        } else {
            ids
        }
    }
}

/// The front matter of one page. Deliberately a few lines rather than a YAML dependency: the grammar is
/// `key: scalar` and `key: [a, b]`, and a parser that accepts more than the pages use would accept a page the
/// checks below cannot read.
fn parse(path: &Path, root: &Path) -> Option<Page> {
    let text = std::fs::read_to_string(path).ok()?;
    let body = text.strip_prefix("---\n")?;
    let end = body.find("\n---\n")?;
    let mut fields = BTreeMap::new();
    for line in body[..end].lines() {
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let (key, value) = (key.trim(), value.trim());
        if key.is_empty() || value.is_empty() {
            continue;
        }
        let field = match value.strip_prefix('[').and_then(|v| v.strip_suffix(']')) {
            Some(inner) => Field::List(
                inner
                    .split(',')
                    .map(|item| item.trim().to_string())
                    .filter(|item| !item.is_empty())
                    .collect(),
            ),
            None => Field::Scalar(value.to_string()),
        };
        fields.insert(key.to_string(), field);
    }
    let relative = path
        .strip_prefix(root.join("features"))
        .ok()
        .map(|rest| rest.to_string_lossy().replace('\\', "/"))
        .unwrap_or_default();
    Some(Page {
        id: path.file_stem()?.to_string_lossy().to_string(),
        relative,
        label: path
            .strip_prefix(root)
            .ok()?
            .to_string_lossy()
            .replace('\\', "/"),
        fields,
    })
}

/// Every `.md` under `dir`, deepest-last and sorted, so a generated index is byte-identical between runs.
fn markdown_files(dir: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return found;
    };
    let mut entries: Vec<PathBuf> = entries.flatten().map(|entry| entry.path()).collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            found.extend(markdown_files(&path));
        } else if path.extension().is_some_and(|ext| ext == "md") {
            found.push(path);
        }
    }
    found
}

/// Every page with front matter, in a stable order.
fn pages() -> Vec<Page> {
    let root = docs_dir();
    markdown_files(&root)
        .iter()
        .filter_map(|path| parse(path, &root))
        .collect()
}

/// The pages under `docs/features/`, which are the ones the checks below hold to the registries.
fn feature_pages() -> Vec<Page> {
    pages()
        .into_iter()
        .filter(|page| !page.relative.is_empty())
        .collect()
}

/// The generated pages, paired with the path each is committed as.
fn generated() -> Vec<(&'static str, String)> {
    vec![
        ("reference/commands.md", commands_page()),
        (
            "reference/config.md",
            config_page().expect("the config reference generates"),
        ),
        ("reference/dependencies.md", dependencies_page()),
        ("features/README.md", feature_index(&feature_pages())),
    ]
}

/// The check that makes a checked-in generated file safe to have: a command added to the table, a key added to
/// the config or a page added to `docs/features/` without regenerating fails here rather than shipping a
/// reference that quietly lies.
///
/// `UPDATE_DOCS=1 cargo test -p hyprshell --lib docs` rewrites them.
#[test]
fn the_committed_reference_matches_what_this_build_generates() {
    for (file, generated) in generated() {
        let path = docs_dir().join(file);
        if std::env::var_os("UPDATE_DOCS").is_some() {
            std::fs::create_dir_all(path.parent().expect("a parent directory")).expect("create it");
            std::fs::write(&path, &generated).expect("write the page");
            continue;
        }
        let on_disk = std::fs::read_to_string(&path).unwrap_or_default();
        assert_eq!(
            on_disk, generated,
            "docs/{file} is out of date; regenerate with \
             `UPDATE_DOCS=1 cargo test -p hyprshell --lib docs`"
        );
    }
}

/// Front matter is only worth having if it cannot lie. Every id a page names has to exist in the registry that
/// owns it, which is what makes "does this feature need a Wayland protocol?" answerable from the page and
/// correct.
#[test]
fn every_page_names_ids_that_exist() {
    let dep_ids: BTreeSet<&str> = deps::ALL.iter().map(|entry| entry.id).collect();
    let target_names: BTreeSet<&str> = TARGETS.iter().map(|target| target.name).collect();
    let sections: BTreeSet<String> = toml::Value::try_from(config::Config::starter())
        .expect("the default config serializes")
        .as_table()
        .expect("the default config is a table")
        .keys()
        .cloned()
        .collect();

    for page in pages() {
        for id in page.list("deps") {
            assert!(
                dep_ids.contains(id.as_str()),
                "{}: '{id}' is not a dependency id — see crates/util/src/deps.rs",
                page.label
            );
        }
        for target in page.list("commands") {
            assert!(
                target_names.contains(target.as_str()),
                "{}: '{target}' is not an IPC target — see `hyprshell --list`",
                page.label
            );
        }
        for section in page.list("config") {
            assert!(
                sections.contains(&section),
                "{}: '[{section}]' is not a config section — see `hyprshell config schema`",
                page.label
            );
        }
    }
}

/// The vocabulary of the front matter itself. A typo in `kind` would silently drop a page out of the index,
/// which is the one failure a generated index cannot show you.
#[test]
fn every_page_declares_a_known_kind_and_status() {
    for page in pages() {
        let kind = page.kind();
        assert!(
            ["module", "surface", "system", "theming", "guide"].contains(&kind),
            "{}: '{kind}' is not a page kind",
            page.label
        );
        if let Some(status) = page.scalar("status") {
            assert!(
                ["stable", "partial", "planned"].contains(&status),
                "{}: '{status}' is not a status",
                page.label
            );
        }
        if let Some(compositor) = page.scalar("compositor") {
            assert!(
                ["any", "hyprland"].contains(&compositor),
                "{}: '{compositor}' is not a compositor requirement",
                page.label
            );
        }
        assert!(
            page.scalar("title").is_some_and(|t| !t.is_empty()),
            "{}: every page needs a title",
            page.label
        );
        assert!(
            page.scalar("summary").is_some_and(|s| !s.is_empty()),
            "{}: every page needs a one-line summary — the index prints it",
            page.label
        );
    }
}

/// A module a user can put on a bar and cannot read about is the gap this catches, and it closes in both
/// directions: a page for a module that no longer exists is just as wrong as a module with no page.
#[test]
fn every_module_has_a_page_and_every_module_page_has_a_module() {
    let popouts = crate::core::popouts::default_popouts();
    let registry = crate::core::registry::default_registry(&popouts);
    let registered: BTreeSet<String> = registry.iter().map(|(id, _)| id.to_string()).collect();

    let documented: BTreeSet<String> = feature_pages()
        .iter()
        .filter(|page| page.kind() == "module")
        .flat_map(|page| page.module_ids())
        .collect();

    for id in &registered {
        assert!(
            documented.contains(id),
            "module '{id}' is registered and has no page under docs/features/modules/"
        );
    }
    for id in &documented {
        assert!(
            registered.contains(id),
            "docs/features/modules/ describes '{id}', which is not a registered module"
        );
    }
}

/// A dependency nobody documents is one a user has no way to know they want. The row already says what its
/// absence costs; this is what makes some page say what to do about it.
#[test]
fn every_dependency_is_claimed_by_a_page() {
    let claimed: BTreeSet<String> = pages().iter().flat_map(|page| page.list("deps")).collect();
    for entry in deps::ALL {
        assert!(
            claimed.contains(entry.id),
            "'{}' is a dependency no page names in its front matter",
            entry.id
        );
    }
}
