//! The annotated default config, generated rather than written.
//!
//! `hyprshell config schema` prints every section with its defaults and the doc comment that explains it, so the
//! "every option" reference is a view of the code instead of a second copy that drifts away from it. The comments
//! come from `build.rs`, which lifts them off `config.rs`; the values come from serializing [`Config::starter`], so
//! a key that exists is a key the shell reads.

use std::collections::HashMap;
use std::fmt::Write;

use crate::core::config::Config;

include!(concat!(env!("OUT_DIR"), "/config_docs.rs"));

/// Which config struct backs each top-level section, so a section's keys can be annotated from the right
/// struct. Kept honest by `every_section_maps_to_a_documented_struct`, which fails if a section is added to
/// `Config` without an entry here.
fn section_structs() -> HashMap<&'static str, &'static str> {
    [
        ("general", "GeneralConfig"),
        ("bars", "BarsConfig"),
        ("theme", "ThemeConfig"),
        ("shape", "ShapeConfig"),
        ("corners", "CornersConfig"),
        ("panels", "PanelsConfig"),
        ("popouts", "PopoutsConfig"),
        ("osd", "OsdConfig"),
        ("icons", "IconsConfig"),
        ("notifications", "NotificationsConfig"),
        ("toasts", "ToastsConfig"),
        ("screenshot", "ScreenshotConfig"),
        ("recorder", "RecorderConfig"),
        ("utilities", "UtilitiesConfig"),
        ("sidebar", "SidebarConfig"),
        ("background", "BackgroundConfig"),
        ("wallpaper", "WallpaperConfig"),
        ("active_window", "ActiveWindowConfig"),
        ("clock", "ClockConfig"),
        ("media", "MediaConfig"),
        ("lyrics", "LyricsConfig"),
        ("workspaces", "WorkspacesConfig"),
        ("launcher", "LauncherConfig"),
        ("audio", "AudioConfig"),
        ("visualiser", "VisualiserConfig"),
        ("brightness", "BrightnessConfig"),
        ("temperature", "TemperatureConfig"),
        ("battery", "BatteryConfig"),
        ("lock_status", "LockStatusConfig"),
        ("lock", "LockConfig"),
        ("idle", "IdleConfig"),
        ("status_icons", "StatusIconsConfig"),
        ("network", "NetworkConfig"),
        ("bluetooth", "BluetoothConfig"),
        ("gpu", "GpuConfig"),
        ("weather", "WeatherConfig"),
        ("dashboard", "DashboardConfig"),
        ("paths", "PathsConfig"),
        ("tray", "TrayConfig"),
        ("animation", "AnimationConfig"),
        ("keynav", "KeyNavConfig"),
    ]
    .into_iter()
    .collect()
}

fn doc_for(structure: &str, field: &str) -> Option<&'static str> {
    CONFIG_DOCS
        .iter()
        .find(|(s, f, _)| *s == structure && *f == field)
        .map(|(_, _, doc)| *doc)
}

/// Every documented key, as `# ` comment lines wrapped to nothing — the source comments are already wrapped,
/// so they are emitted verbatim rather than reflowed into a width this shell would have to guess.
fn comment(doc: &str, indent: &str) -> String {
    doc.lines()
        .map(|line| {
            if line.is_empty() {
                format!("{indent}#\n")
            } else {
                format!("{indent}# {line}\n")
            }
        })
        .collect()
}

/// The annotated default config, or one section of it. An unknown section name is an error listing the real
/// ones, so a typo answers with the menu rather than with nothing.
pub fn render(section: Option<&str>) -> Result<String, String> {
    let structs = section_structs();
    let defaults = toml::Value::try_from(Config::starter())
        .map_err(|e| format!("serializing the default config: {e}"))?;
    let table = defaults
        .as_table()
        .ok_or_else(|| "the default config is not a table".to_string())?;

    if let Some(name) = section
        && !structs.contains_key(name)
    {
        let mut known: Vec<&str> = structs.keys().copied().collect();
        known.sort_unstable();
        return Err(format!(
            "unknown section '{name}'; known sections: {}",
            known.join(", ")
        ));
    }

    let mut out = String::new();
    if section.is_none() {
        out.push_str("# hyprshell configuration reference\n");
        out.push_str(
            "#\n# Generated by `hyprshell config schema` from this build's own defaults.\n",
        );
        out.push_str("# Every key below is the value the shell uses when the key is absent.\n\n");
        let _ = writeln!(out, "version = {}\n", crate::core::config::CONFIG_VERSION);
    }

    // The order `Config` declares its sections in, which is the order a reader meets them in the source.
    for (name, structure) in ordered_sections(&structs) {
        if section.is_some_and(|wanted| wanted != name) {
            continue;
        }
        let Some(value) = table.get(name) else {
            continue;
        };
        if let Some(doc) = doc_for(structure, "") {
            out.push_str(&comment(doc, ""));
        }
        let _ = writeln!(out, "[{name}]");
        out.push_str(&render_section(name, value, structure));
        out.push('\n');
    }
    Ok(out)
}

/// A section's keys: each documented field's comment, then the key and its default. Nested tables
/// (`[theme.scale]`, `[background.clock]`) and lists of tables are emitted after the flat keys, which is the
/// order TOML requires — a `[theme.scale]` header printed before `[theme]`'s own keys would swallow them.
fn render_section(section: &str, value: &toml::Value, structure: &str) -> String {
    let Some(table) = value.as_table() else {
        return String::new();
    };
    let mut out = String::new();
    let mut nested = String::new();
    let mut arrays = String::new();
    for (key, entry) in table {
        if let Some(inner) = entry.as_table() {
            nested.push_str(&render_nested(
                &format!("{section}.{key}"),
                inner,
                doc_for(structure, key),
                type_of(structure, key),
            ));
            continue;
        }
        if let Some(doc) = doc_for(structure, key) {
            out.push_str(&comment(doc, ""));
        }
        // A list of tables (`[[battery.warn_levels]]`, `[[idle.stages]]`) has to carry its section in the
        // header and has to come after the section's flat keys — serializing it as a bare one-key map gets
        // both wrong, and yields a reference whose own text does not parse back into the section it documents.
        if let Some(entries) = table_array(entry) {
            for element in entries {
                let _ = writeln!(arrays, "\n[[{section}.{key}]]");
                arrays.push_str(&toml::to_string(element).unwrap_or_default());
            }
            continue;
        }
        let rendered = toml::to_string(&toml::map::Map::from_iter([(
            key.clone(),
            narrow_float(entry),
        )]))
        .unwrap_or_default();
        out.push_str(&rendered);
    }
    out.push_str(&render_unset(table, structure));
    out.push_str(&nested);
    out.push_str(&arrays);
    out
}

/// One nested table, headed and annotated from the struct that backs it.
///
/// A map-valued key (`[theme.colors]`, `[background.monitors]`) has no struct and no fixed keys, so it is
/// printed as an empty header — which is still the right answer: it tells a reader the table exists and what to
/// call it, which is exactly what they cannot learn anywhere else.
fn render_nested(
    path: &str,
    table: &toml::map::Map<String, toml::Value>,
    doc: Option<&'static str>,
    structure: Option<&'static str>,
) -> String {
    let mut out = String::from("\n");
    if let Some(doc) = doc {
        out.push_str(&comment(doc, ""));
    }
    let _ = writeln!(out, "[{path}]");
    let Some(structure) = structure else {
        return out;
    };
    let mut deeper = String::new();
    for (key, entry) in table {
        if let Some(inner) = entry.as_table() {
            deeper.push_str(&render_nested(
                &format!("{path}.{key}"),
                inner,
                doc_for(structure, key),
                type_of(structure, key),
            ));
            continue;
        }
        if let Some(doc) = doc_for(structure, key) {
            out.push_str(&comment(doc, ""));
        }
        out.push_str(
            &toml::to_string(&toml::map::Map::from_iter([(
                key.clone(),
                narrow_float(entry),
            )]))
            .unwrap_or_default(),
        );
    }
    out.push_str(&render_unset(table, structure));
    out.push_str(&deeper);
    out
}

/// The struct backing `structure::field`, when the field is a plain nested config struct.
fn type_of(structure: &str, field: &str) -> Option<&'static str> {
    CONFIG_FIELD_TYPES
        .iter()
        .find(|(owner, name, _)| *owner == structure && *name == field)
        .map(|(_, _, kind)| *kind)
}

/// The struct backing a section path — `background` or `background.clock` — by walking the field types.
fn struct_for(path: &str) -> Option<&'static str> {
    let mut parts = path.split('.');
    let mut current = *section_structs().get(parts.next()?)?;
    for part in parts {
        current = type_of(current, part)?;
    }
    Some(current)
}

/// Whether the config section at `path` has a key — or a key's explanation — containing `needle`, which the
/// caller has already lowercased.
///
/// This is what the settings search matches against. Every form's fields are keys on a struct and every key's
/// prose is already lifted off the source for the reference, so a search built on it finds a setting by the
/// words that *explain* it without any form having to register its rows a second time — and cannot go stale
/// when a form gains one.
pub fn section_mentions(path: &str, needle: &str) -> bool {
    let Some(structure) = struct_for(path) else {
        return false;
    };
    CONFIG_DOCS.iter().any(|(owner, field, doc)| {
        *owner == structure
            && (field.to_lowercase().contains(needle) || doc.to_lowercase().contains(needle))
    })
}

/// An `f32` config value printed the way it was written rather than the way it widens.
///
/// Serde has one float type and it is `f64`, so `0.35f32` reaches the serializer as `0.3499999940395355` and
/// the generated reference documents a default nobody typed. The test for "this came from an `f32`" is that
/// narrowing round-trips exactly — true for every value an `f32` field can hold and false for a `f64` carrying
/// more precision than one, which is left alone.
fn narrow_float(entry: &toml::Value) -> toml::Value {
    match entry.as_float() {
        Some(value) if (value as f32) as f64 == value => {
            toml::Value::Float((value as f32).to_string().parse().unwrap_or(value))
        }
        _ => entry.clone(),
    }
}

/// `entry` as a non-empty array of tables, which is the one shape that needs its own header.
fn table_array(entry: &toml::Value) -> Option<&[toml::Value]> {
    let array = entry.as_array()?;
    (!array.is_empty() && array.iter().all(toml::Value::is_table)).then_some(array.as_slice())
}

/// The keys serde left out because they default to `None`.
///
/// An `Option` with no value serializes to nothing, so a reference built from the defaults alone would silently
/// omit every optional key — `[clock] format` is a documented option a reader would never learn exists. They
/// are emitted commented out, since there is no default to print and writing one would invent a value the
/// shell does not use.
fn render_unset(table: &toml::map::Map<String, toml::Value>, structure: &str) -> String {
    let mut out = String::new();
    for (owner, field, doc) in CONFIG_DOCS {
        if *owner != structure || field.is_empty() || table.contains_key(*field) {
            continue;
        }
        out.push_str(&comment(doc, ""));
        let _ = writeln!(out, "# {field} =   # unset by default");
    }
    out
}

fn ordered_sections(
    structs: &HashMap<&'static str, &'static str>,
) -> Vec<(&'static str, &'static str)> {
    let mut sections: Vec<(&'static str, &'static str)> =
        structs.iter().map(|(k, v)| (*k, *v)).collect();
    sections.sort_unstable_by_key(|(name, _)| *name);
    sections
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_section_on_config_has_a_struct_in_the_map() {
        // The one way this file goes stale: a section added to `Config` and never mapped here, which would silently drop it from the reference the README points at.
        let defaults = toml::Value::try_from(Config::starter()).unwrap();
        let table = defaults.as_table().unwrap();
        let structs = section_structs();
        let missing: Vec<&str> = table
            .keys()
            .map(String::as_str)
            .filter(|key| *key != "version" && *key != "modules")
            .filter(|key| !structs.contains_key(key))
            .collect();
        assert!(
            missing.is_empty(),
            "sections with no struct mapped: {missing:?}"
        );
    }

    #[test]
    fn the_schema_carries_the_doc_comments_off_the_source() {
        let text = render(None).expect("renders");
        assert!(text.contains("[notifications]"));
        assert!(text.contains("[animation]"));
        assert!(
            text.contains("# "),
            "the schema is annotated, not a bare dump of defaults"
        );
        // A value, not a placeholder: the defaults come from the code, so they cannot disagree with it.
        assert!(text.contains("max_visible = 4"), "{text}");
        // And it round-trips: what the reference prints is a config the shell would accept.
        let parsed: Config = toml::from_str(&text).expect("the printed schema parses");
        assert_eq!(parsed.notifications.max_visible, 4);
    }

    #[test]
    fn an_f32_default_is_printed_as_it_was_written() {
        // Serde has one float type, so every `f32` default reaches the printer widened: `0.35` came out as
        // `0.3499999940395355`, and the reference documented a number nobody typed and no one would copy.
        let text = render(None).expect("renders");
        assert!(text.contains("background_opacity = 0.35"), "{text}");
        assert!(text.contains("beat_sensitivity = 1.35"), "{text}");
        assert!(
            !text.contains("0.3499999"),
            "a widened f32 is still being printed: {text}"
        );
        // And the shorter spelling still parses back to the same value the code holds.
        let parsed: Config = toml::from_str(&text).expect("the printed schema parses");
        assert_eq!(
            parsed.background.clock.background_opacity,
            Config::starter().background.clock.background_opacity
        );
    }

    #[test]
    fn a_list_of_tables_is_printed_under_the_section_that_owns_it() {
        // Round-tripping is not enough on its own to catch this: a bare `[[stages]]` parses as an unknown
        // top-level key, which serde drops silently — so the reference read as valid while documenting a
        // section the shell would never see.
        let text = render(Some("idle")).expect("renders");
        assert!(text.contains("[[idle.stages]]"), "{text}");
        assert!(!text.contains("\n[[stages]]"), "{text}");

        let parsed: Config = toml::from_str(&text).expect("the printed section parses");
        let printed = Config::starter().idle.stages;
        assert_eq!(parsed.idle.stages.len(), printed.len());
        assert_eq!(parsed.idle.stages[0].action, printed[0].action);

        // The same shape one section over, so the fix is not one special case.
        let battery = render(Some("battery")).expect("renders");
        assert!(battery.contains("[[battery.warn_levels]]"), "{battery}");
    }

    #[test]
    fn one_section_can_be_asked_for_and_a_typo_lists_the_rest() {
        let one = render(Some("clock")).expect("renders");
        assert!(one.contains("[clock]"));
        assert!(
            !one.contains("[notifications]"),
            "only the section asked for"
        );

        let err = render(Some("clok")).expect_err("a typo is an error");
        assert!(err.contains("unknown section 'clok'"), "{err}");
        assert!(err.contains("clock"), "and it lists the real ones: {err}");
    }
}
